[package]
name = "decishell"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[worksoace]
members = [
    "crates/*"
]


[dependencies]
deci-parser = {version="0.0.1",path="./crates/deci-parser"}